### ISSUE TITLE
autofill.exe skips card slots when uploading

### ISSUE THREAD

**Issue by keysharpener** [ndepaola/mpc-autofill#20]
Hi,

First, thanks again for this great tool that has helped me a lot ordering decks a few months ago. 

I'm trying again these days, using the new build, and I'm encountering issues. Cards seem to be skipped unpredictably. There are blank cards and cards that seem shuffled a few positions after their expected one.

I've had issues with other deck uploads, but this one is definitely the worst, with dozens of blank spaces.

![image](https://user-images.githubusercontent.com/6585721/117877289-ac4c6300-b2a4-11eb-8e87-a8014d0f748e.png)
![image](https://user-images.githubusercontent.com/6585721/117877484-eae21d80-b2a4-11eb-9039-1b3ebdae4a24.png)

Do you have any idea where it could come from? MPC seems to have performance issues with days, maybe it's related.

You can find the xml enclosed.

[cards.txt](https://github.com/ndepaola/mpc-autofill/files/6461695/cards.txt)

Thanks in advance for your help

**Comment by Nickola-FR** [comment]
Hello,
Very useful piece of code, but I'm in the same situation OP.
When prepraring an order (mostly 100 items), I get a lot of blanks that need to be uploaded manually.
Thanks for your help.

**Comment by Nickola-FR** [comment]
Hello,
I've noticed 2 things recently.
- upload times have come severly up. I often see upload at "280+ s/it" in the software window
- The software threads images uploads, isn't it ? At the end of the upload, autofill.exe reports images it wasn't able to get uploaded. But checking after an upload, the files stated in the list were indeed OK, but other files were missing but not reported. 

The latter being directly related with the behaviour you described.

The timeout is a good thing to begin with, as if you remove it, the software might wait indefinitely. Maybe you could make it longer (like 5 minutes). And after that, would it be possible to implement a check for the status of the uploaded image on the site ? It'll definitely have an impact on the upload time.

I have another question, but it's more functionnality request.

Thanks for your work.

Regards,

Nickola

**Comment by ndepaola** [comment]
i've also noticed the drastic increase in upload times - my recent 612 card order took a shocking 16 hours to upload. the code for image uploading has barely changed since the project's initial release though, so i wonder if this increase is something on MPC's side? perhaps they think we're spamming their servers and are throttling uploads from automated browsers.

in terms of the timeout, were you thinking that the script would cancel the upload after 5 minutes? i'm not sure if an image taking a long time to upload can lock the script though - the script only begins waiting for an image to finish uploading if it sees the upload progress bar appear, and since all images the script can download are smaller than MPC's max image size, there should never be a case where an image continues to upload indefinitely. unless the case you have in mind is if the script misses the fact that an image finished uploading?

feel free to let me know here what the feature request is too!

**Comment by keysharpener** [comment]
You've saved us a lot of time on other orders, and it's a free tool. Don't worry, we're very grateful even if there are a few bugs. The point you are raising is also on point, maybe MPC is throttling the uploads when using the automated testing software.
I can help test your version without timeout (or with a longer one) if you wish. I still have decks to upload.

**Comment by ndepaola** [comment]
the latest release should solve this issue - could I get you guys @keysharpener and @Nickola-FR to test it out when you have some spare time please? i'll mark this issue as resolved if everything looks good!

**Comment by Nickola-FR** [comment]
I'll start a test in few minutes, and let you know when it'll be finished (later this evening, or tomorrow in the morning)

**Comment by Nickola-FR** [comment]
Confirmed. I uploaded an EDH Deck for testing. All 103 images uploaded, no problem, none missing.

**Comment by ndepaola** [comment]
excellent! glad to hear it

**Comment by keysharpener** [comment]
I confirm that it's fine on my side too. Thanks
